import { Router } from "express";
import { authenticateJWT } from "../middleware/auth.middleware.js";
import * as taskController from "../controllers/task.controller.js";
const router = Router();
router.get("/", authenticateJWT, taskController.getAllTasks);
router.get("/:id", authenticateJWT, taskController.getTaskById);
router.post("/", authenticateJWT, taskController.createTask);
router.put("/:id", authenticateJWT, taskController.updateTask);
router.delete("/:id", authenticateJWT, taskController.deleteTask);
export default router;
